### ISSUE TITLE
Ubuntu下DPABI调用matlab内置函数movefile报错

### ISSUE THREAD

**Issue by feiwujia** [Chaogan-Yan/DPABI#65]
尊敬的严超赣老师，

非常感谢您开发的DPABI工具包，为功能核磁共振提供了一键式处理方案。
近期在使用DPASRF时候碰到了报错：
```
Error using DPARSFA_run (line_5052)
/bin/bash: /bin/mv: Argument list too long
```
在网上搜索之后发现，是由于DPARSFA_run.m中复制文件使用matlab内置函数movefile，而movefile调用Ubuntu的mv，导致的这个报错，以下是一些基本情况：

系统：ubuntu 18.04 LTS
matlab版本：R2018b
DPABI版本：V6.2_220915
受试者个数：400个
FC_ROI模板选择：[Schaefer2018_400Parcels_7Networks_order_FSLMNI152_1mm.nii](https://github.com/Chaogan-Yan/DPABI/blob/e60420e4d38921286c2d13de16e7bfbb55491332/Templates/Schaefer2018_400Parcels_7Networks_order_FSLMNI152_1mm.nii)

在DPABI7.0的代码中是[5060行](https://github.com/Chaogan-Yan/DPABI/blob/e60420e4d38921286c2d13de16e7bfbb55491332/DPARSF/DPARSFA_run.m#L5060)，使用的仍然是movefile函数。
这个错误不同于在[macOS中的问题](http://rfmri.org/content/binmv-argument-list-too-long-macbook)出现错误之后，Results和ResultsS文件夹里有关FC的文件夹均为空，导致后续FC分析无法运行，因本人水平有限，未能读懂DPARSF代码逻辑，望严老师在百忙之中优化代码，非常感谢！

**Comment by Chaogan-Yan** [comment]
请在http://rfmri.org提问。你的问题是Define ROI太多，同时又选了Functional Connectivity，生成文件太多了。
