### ISSUE TITLE
关于SMA的cut-off设置的问题

### ISSUE THREAD

**Issue by ATP-BME** [Chaogan-Yan/DPABI#72]
严老师您好！
新版本的DPABI中增加了多站点协调的方法，在尝试使用SMA对多站点数据进行协调时，需要设置Z变量的cutoff。请问对于年龄等连续型变量，cutoff的值应该怎样设置呢？这个阈值对算法的影响是什么？

**Comment by dianewyw** [comment]
ATP-BME你好，

在使用SMA对多站点数据进行协调时，对于年龄等连续型变量，cutoff值主要受你的研究问题决定。

比如，你的因变量（e.g. 大脑皮层厚度）受年龄影响，即年龄对你的因变量有一个因果影响，你可以设置一个或多个cut-off值，这些值主要参考已有的研究和你的假设去设置，比如假设已有研究中说50岁前后的群体在大脑皮层厚度上有显著的差异，那你就可以输入50；如果你这批被试当中年龄范围是30-35，你可能假设认为大脑皮层厚度在这个阶段受年龄影响不大，那么你可以不对年龄进行cut-off。

理论上你的cut-off越多，你的结果会更加具体和精细。但是这会要求你的样本量足够多（你的target站点的不同年龄段的样本量要足够多，另外你需要矫正的source站点里每个划分的年龄段的人也不能少于3个），另外对计算性能的要求也很高。

希望以上能够解答你的疑惑。

P.S.如果你要设置分类变量，在cutoff中填0即可。

**Comment by Chaogan-Yan** [comment]
I close this issue then. You may also discuss DPABI related questions at https://rfmri.org/DPABIDiscussion
